### ISSUE TITLE
can not create db

### ISSUE THREAD

**Issue by sam-mix** [Aristat/golang-example-app#4]
```zsh
❯ make createdb
createdb golang_example_development
make: createdb: No such file or directory
make: *** [createdb] Error 1
```

**Comment by Aristat** [comment]
Hey, it's short commands in PostgreSQL https://www.postgresql.org/docs/13/reference-client.html, as first you need to install PostgreSQL to your laptop https://www.postgresql.org/download/. If you already have it installed but only have the `psql` command, you can create the database yourself via the console without using make

**Comment by sam-mix** [comment]
thanks
